In [1]:
import pandas as pd

In [3]:
from mlxtend.frequent_patterns import apriori
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import association_rules

In [5]:
import warnings
warnings.filterwarnings("ignore")

In [23]:
df = pd.read_csv("sepet.csv", names=['products'], header=None, encoding="ISO-8859-1")

In [25]:
df

                           products
0      ekmek;sut;cerez;salca;peynir
1   bebek bezi;ekmek;yumurta;peynir
2         kola;sut;bebek bezi;ekmek
3         bebek bezi;sut;kola;cerez
4        sut;cerez;ekmek;bebek bezi
5      ekmek;bebek bezi;sut;yumurta
6      ekmek;sut;yumurta;seker;kola
7       kola;ekmek;bebek bezi;salca
8  su;islak mendil;deterjan;supurge

In [27]:
df.shape

(9, 1)

In [31]:
df.columns

Index(['products'], dtype='object')

In [33]:
df.values

array([['ekmek;sut;cerez;salca;peynir'],
       ['bebek bezi;ekmek;yumurta;peynir'],
       ['kola;sut;bebek bezi;ekmek'],
       ['bebek bezi;sut;kola;cerez'],
       ['sut;cerez;ekmek;bebek bezi'],
       ['ekmek;bebek bezi;sut;yumurta'],
       ['ekmek;sut;yumurta;seker;kola'],
       ['kola;ekmek;bebek bezi;salca'],
       ['su;islak mendil;deterjan;supurge']], dtype=object)

In [41]:
data = list(df["products"].apply(lambda x:x.split(';')))
data

[['ekmek', 'sut', 'cerez', 'salca', 'peynir'],
 ['bebek bezi', 'ekmek', 'yumurta', 'peynir'],
 ['kola', 'sut', 'bebek bezi', 'ekmek'],
 ['bebek bezi', 'sut', 'kola', 'cerez'],
 ['sut', 'cerez', 'ekmek', 'bebek bezi'],
 ['ekmek', 'bebek bezi', 'sut', 'yumurta'],
 ['ekmek', 'sut', 'yumurta', 'seker', 'kola'],
 ['kola', 'ekmek', 'bebek bezi', 'salca'],
 ['su', 'islak mendil', 'deterjan', 'supurge']]

In [43]:
te = TransactionEncoder()

In [47]:
te_data = te.fit(data).transform(data)
df = pd.DataFrame(te_data, columns=te.columns_)
df

,bebek bezi,cerez,deterjan,ekmek,islak mendil,kola,peynir,salca,seker,su,supurge,sut,yumurta
0,False,True,False,True,False,False,True,True,False,False,False,True,False
1,True,False,False,True,False,False,True,False,False,False,False,False,True
2,True,False,False,True,False,True,False,False,False,False,False,True,False
3,True,True,False,False,False,True,False,False,False,False,False,True,False
4,True,True,False,True,False,False,False,False,False,False,False,True,False
5,True,False,False,True,False,False,False,False,False,False,False,True,True
6,False,False,False,True,False,True,False,False,True,False,False,True,True
7,True,False,False,True,False,True,False,True,False,False,False,False,False
8,False,False,True,False,True,False,False,False,False,True,True,False,False

In [49]:
df1 = apriori(df, min_support=0.02, use_colnames=True, verbose=1)
df1

Processing 6 combinations | Sampling itemset size 6 5

      support                            itemsets
0    0.666667                        (bebek bezi)
1    0.333333                             (cerez)
2    0.111111                          (deterjan)
3    0.777778                             (ekmek)
4    0.111111                      (islak mendil)
..        ...                                 ...
101  0.111111         (sut, salca, ekmek, peynir)
102  0.111111        (sut, yumurta, seker, ekmek)
103  0.111111         (sut, kola, seker, yumurta)
104  0.111111  (cerez, peynir, sut, ekmek, salca)
105  0.111111  (yumurta, seker, sut, kola, ekmek)

[106 rows x 2 columns]

In [51]:
association_rules(df1, metric="confidence", min_threshold=0.6)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(cerez),(bebek bezi),0.333333,0.666667,0.222222,0.666667,1.000000,0.000000,1.000000,0.000
1,(bebek bezi),(ekmek),0.666667,0.777778,0.555556,0.833333,1.071429,0.037037,1.333333,0.200
2,(ekmek),(bebek bezi),0.777778,0.666667,0.555556,0.714286,1.071429,0.037037,1.166667,0.300
3,(kola),(bebek bezi),0.444444,0.666667,0.333333,0.750000,1.125000,0.037037,1.333333,0.200
4,(sut),(bebek bezi),0.666667,0.666667,0.444444,0.666667,1.000000,0.000000,1.000000,0.000
...,...,...,...,...,...,...,...,...,...,...
254,"(kola, yumurta)","(sut, seker, ekmek)",0.111111,0.111111,0.111111,1.000000,9.000000,0.098765,inf,1.000
255,"(sut, seker)","(kola, yumurta, ekmek)",0.111111,0.111111,0.111111,1.000000,9.000000,0.098765,inf,1.000
256,"(kola, seker)","(sut, yumurta, ekmek)",0.111111,0.222222,0.111111,1.000000,4.500000,0.086420,inf,0.875
257,"(seker, ekmek)","(sut, kola, yumurta)",0.111111,0.111111,0.111111,1.000000,9.000000,0.098765,inf,1.000
258,(seker),"(sut, kola, yumurta, ekmek)",0.111111,0.111111,0.111111,1.000000,9.000000,0.098765,inf,1.000

In [55]:
rules=association_rules(df1, metric="confidence", min_threshold=0.6)
rules[(rules['confidence']>=0.8)&(rules['support']>=0.2)&(rules['lift']>=1.0)]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
1,(bebek bezi),(ekmek),0.666667,0.777778,0.555556,0.833333,1.071429,0.037037,1.333333,0.200000
8,(cerez),(sut),0.333333,0.666667,0.333333,1.000000,1.500000,0.111111,inf,0.500000
16,(peynir),(ekmek),0.222222,0.777778,0.222222,1.000000,1.285714,0.049383,inf,0.285714
17,(salca),(ekmek),0.222222,0.777778,0.222222,1.000000,1.285714,0.049383,inf,0.285714
19,(sut),(ekmek),0.666667,0.777778,0.555556,0.833333,1.071429,0.037037,1.333333,0.200000
21,(yumurta),(ekmek),0.333333,0.777778,0.333333,1.000000,1.285714,0.074074,inf,0.333333
35,"(cerez, bebek bezi)",(sut),0.222222,0.666667,0.222222,1.000000,1.500000,0.074074,inf,0.428571
44,"(bebek bezi, yumurta)",(ekmek),0.222222,0.777778,0.222222,1.000000,1.285714,0.049383,inf,0.285714
56,"(cerez, ekmek)",(sut),0.222222,0.666667,0.222222,1.000000,1.500000,0.074074,inf,0.428571
101,"(sut, yumurta)",(ekmek),0.222222,0.777778,0.222222,1.000000,1.285714,0.049383,inf,0.285714